CREATE TABLE orders (
    "Row ID" SERIAL PRIMARY KEY,
    "Order ID" VARCHAR(255),
    "Order Date" DATE,
    "Ship Date" DATE,
    "Ship Mode" VARCHAR(100),
    "Customer ID" VARCHAR(100),
    "Customer Name" VARCHAR(255),
    "Segment" VARCHAR(100),
    "Country" VARCHAR(100),
    "City" VARCHAR(100),
    "State" VARCHAR(100),
    "Postal Code" VARCHAR(20),
    "Region" VARCHAR(50),
    "Product ID" VARCHAR(100),
    "Category" VARCHAR(100),
    "Sub-Category" VARCHAR(100),
    "Product Name" TEXT,
    "Sales" NUMERIC(10, 2),
    "Quantity" INTEGER,
    "Discount" NUMERIC(5, 2),
    "Profit" NUMERIC(10, 2),
    "Order Year" INTEGER,
    "Order Month" INTEGER,
    "Order Month Name" VARCHAR(20),
    "Discount_Bucket" VARCHAR(50)
);